
POST http://localhost:8000/signup/register
Accept: application/json
Content-Type: application/json


{
   
    "email":"hhhhhhh@gmail.com",
  "password":"123456",
  "Cpassword":"123456"

}
###

POST http://localhost:8000/signin/login
Accept: application/json
Content-Type: application/json

{
   
    "email":"harini@gmail.com",
  "password": "harini2"
  

}